baseurl = "http://veganrecipes.aaronberk.ca"
languageCode = "en-gb"
title = "Vegan Recipe Blog"
theme = "hpstr"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
disqusShortname = ""

copyright = "Copyright Aaron Berk 2018 · "

[params]
	subtitle = "A blog for vegan recipes that I make."
	[params.author]
		name = "Aaron Berk"
		avatar = "/images/avatar.jpg"
		bio = "A vegan grad student living in Vancouver."
		github = "asberk"
	[params.image]
	  feature = "/images/abstract-1.jpg"
	  credit = ""
	  creditlink = ""


