* Lentil Bolognese 
  SCHEDULED: <2020-01-13 Mon>

Link to the [[https://www.avantgardevegan.com/recipes/protein-packed-meal-prep/][Gaz Oakley]] page.

Makes 3 meals, generously

** Ingredients 

 * 1 large onion, chopped fine
 * 2 sticks Celery, chopped fine
 * 4 cloves Garlic, minced
 * 1 Carrot. Peeled & chopped fine
 * 1 tbs Dried Mixed Herbs
 * 1 tsp Sea Salt
 * 1 tsp Cracked Black Pepper
 * 1 tbs Miso
 * 2 tbs Tomato Puree
 * 2 tins Cooked Green Lentils
 * 1 tin Chopped Tomatoes
 * 240 ml Water
 * 400g Spelt Spaghetti or Pasta, cooked to packet instructions  

 * Garnish
   * Fresh herbs
   * Grilled Peppers (optional)

** Macros per meal 

 * Calories :: 441
 * Protein :: 23g
 * Carbs :: 80g

** Directions

 * To a large sauce pan placed over a medium heat, add the oil followed by
   onion, celery, garlic & carrot. Sauté for 4-5 minutes or until softened then
   add the mixed herbs.

 * Stir in the miso & tomato puree, then add the lentils followed by the chopped
   tomatoes & water. Turn the heat down low & place a lid on the pan. Then allow
   the bolognese to simmer away for 25 minutes.

 * Once cooked serve with in your containers with your pasta. 

 * This dish will be fine stored in your fridge for up to 4 days, it can be
   reheated in a saucepan or microwave. Do not heat food in plastic.

